## Линейные преобразования

### Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

_Собственный вектор_ оператора $\textbf{A}$ — это такой ненулевой вектор, действие оператора на который сводится к умножению его на число:

$$\textbf{A}x=\lambda x.$$

Число $\lambda$ называется _собственным значением_ этого оператора.

In [2]:
import numpy as np

In [1]:
def is_eig(A):
    w, v = np.linalg.eig(A)
    print(f'Матрица A:\n{A}')
    print(f'Собственные значения:\n{w}')
    print(f'Собственные векторы:\n{v}')

In [10]:
a = np.array([[1, 1], [0, 1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[1 1]
 [0 1]]
Собственные значения:
[1. 1.]
Собственные векторы:
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


### Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что любой вектор считается для него собственным.


найдём собственные значения линейного оператора, составив и решив характеристическое уравнение

$$ \begin{pmatrix} -1-\lambda& 0\\ 0& -1-\lambda \end{pmatrix} = 0$$

$$ \lambda_{1}~=~\lambda_{2} = -1 $$

Найдём собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

Получим:

$$\begin{cases}
-1\cdot x_{1}+0\cdot x_{2}= -x_{1}, \\
0\cdot x_{1}-1\cdot x_{2}= -x_{2}.
\end{cases}$$ 

$$\begin{cases}
x_{1} = x_{1}, \\
x_{2} = x_{2}.
\end{cases}$$

ограничений нет, справедливо для любого вектора.

### Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.


$$ \begin{cases}1+1 = \lambda \cdot 1\\-1+3 = \lambda \cdot 1\end{cases} \Rightarrow \begin{cases} \lambda = 2\\ \lambda = 2\end{cases} $$

In [13]:
A = np.array([[1, 1], [-1, 3]])
is_eig(A)

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


Вектор x=(1,1) является собственным вектором линейного оператора, заданного матрицей A. 

### Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$ \begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix} \begin{pmatrix} 3\\ -3\\ -4 \end{pmatrix} = \lambda \cdot \begin{pmatrix} 3\\ -3\\ -4 \end{pmatrix} $$

$$ \begin{cases}-9 = 3 \cdot \lambda \\9 = -3 \cdot \lambda \\ -12 = -4 \cdot \lambda \end{cases} \Rightarrow \begin{cases}\lambda = -3 \\\lambda = -3 \\ \lambda = 3 \end{cases} $$

Такая система не имеет смысла, следовательно, вектор  𝑥=(3,−3,-4)  не считается собственным вектором линейного оператора, заданного матрицей  𝐴 .