## Матрицы и матричные операции. Часть 1

In [3]:
import numpy as np

### Установите, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найдите размерности полученных матриц:
### а) 𝐴 — матрица 4×2, 𝐵 — матрица 4×2;
### б) 𝐴 — матрица 2×5, 𝐵 — матрица 5×3;
### в) 𝐴 — матрица 8×3, 𝐵 — матрица 3×8;
### г) 𝐴 — квадратная матрица 4×4, 𝐵 — квадратная матрица 4×4.

определить оба произведения 𝐴⋅𝐵 и 𝐵⋅𝐴 можно только тогда, когда число столбцов 𝐴 совпадает с числом строк 𝐵, а число строк 𝐴 — с числом столбцов 𝐵 

а размерность полученных матриц определяется крайними значениями исходных матриц

а) Произведение не определено;
б) Произведение определено, размерность 2х3;
в) Произведение определено, размерность 8х8;
г) Произведение определено, размерность 4х4.

$$ Найдите~ сумму~ и~ произведение~ матриц~ A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} и~ B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}. $$

In [4]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

сложение матриц 

In [5]:
S = A + B
S

array([[ 5, -3],
       [ 3,  5]])

умножение матриц

In [6]:
A.dot(B)

array([[  4, -11],
       [ 12,  -3]])

$$ Из~ закономерностей~ сложения~ и~ умножения~ матриц~ на~ число~ можно~ сделать~ вывод,~ что~ матрицы~ одного~ размера~ образуют~ линейное~ пространство.~ Вычислите~ линейную~ комбинацию~ 3A-2B+4C~ для~ матриц~ A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}, B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}, C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}. $$

будем использовать умножение число на матрицу

In [7]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

$$ Дана~ матрица~ A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}.
Вычислите~ AA^{T}~ и~ A^{T}A. $$

При транспонировании строки исходной матрицы становятся столбцами, а столбцы — строками

In [9]:
A = np.array([[4, 1], [5, -2], [2, 3]])
At = A.T
A.dot(At)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [10]:
At.dot(A)

array([[45,  0],
       [ 0, 14]])

### Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


a) матрица 2x2, перемножаем по диагонали

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^{2}x - (-cos^{2}x) = 1 $$

б) 

In [5]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{B}')
print(f'Определитель:\n{np.linalg.det(B):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


в)

In [6]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{C}')
print(f'Определитель:\n{np.linalg.det(C):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


### Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) 

$det(A^{2})$ = 16

б) из свойства определителей, определитель транспонированной матрицы равен определителю исходной

$det(A^{T})$ = 4

в) в данном случае матрица А умножается на 2, тогда опредилитель данной матрицы умножается на 2 в степени колл-ва строк в матрице.

$det(2A)$ = $det(A) * 2^{n}$

### Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица называется сингулярной или вырожденной, если её определитель равен нулю

In [7]:
D = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{D}')
print(f'Определитель:\n{np.linalg.det(D):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


В данном случае определитель равен 0, это означает что матрица является вырожденной.

### Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

a)

In [10]:
A = np.matrix('1, 2, 3; 1, 1, 1; 2, 3, 4')
np.linalg.matrix_rank(A)

2