## Системы линейных уравнений

### Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

переведем данную систему уравнений в матрицу, далее путем операций со строками приведем ее к матрице треугольного вида, что позволит нам вычислить последнею переменную а дальше путем подстановок найти остальные

In [1]:
import numpy as np

In [2]:
def gauss_method(A, b, n):
    rnk_A = np.linalg.matrix_rank(A)
    rnk_Ab = np.linalg.matrix_rank(np.hstack((A, b)))
    if  rnk_A == rnk_Ab == n:
        return 'Cистема имеет единственное решение'
    elif (rnk_A == rnk_Ab) and (rnk_A < n):
        return 'Cистема имеет бесконечное колличество решений'
    elif rnk_A < rnk_Ab:
        return 'Cистема несовместна'

In [3]:
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
b = np.array([0, -2, 4]).reshape(-1, 1)
gauss_method(A, b, 4)

'Cистема имеет бесконечное количество решений'

Последняя строка стала нулевой, что позволяет нам убрать её из матрицы, соответственно получилось что переменных больше чем уравнений, а это означает что система имеет бесконечное колличество решений.

### Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

а)

In [4]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, 17, 0]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема имеет единственное решение'

система совместна и является определенной, вектор b(4,17,0) можно выразить через исходные вектора

In [5]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема несовместна'

In [ ]:
система несовместна и не имеет решения, вектор b(1,-2,5) нельзя выразить через исходные вектора

In [6]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема имеет бесконечное количество решений'

### Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [7]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1]).reshape(-1, 1)
gauss_method(A, b, 4)

'Cистема имеет единственное решение'

### Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

представить систему линейных уравнений через линейную комбинацию векторов коэффициентов:

$$x_{1}\begin{pmatrix}
1\\ 
4\\
7
\end{pmatrix}+
x_{2}\begin{pmatrix}
2\\ 
5\\
8
\end{pmatrix}+
x_{2}\begin{pmatrix}
3\\ 
6\\
9
\end{pmatrix} $$

В таком представлении вектор свободных членов  𝑏  считается линейной комбинацией векторов  𝑎1,𝑎2...,𝑎𝑚  с коэффициентами  𝑥1,𝑥2...,𝑥𝑛 .

Векторы коэффициентов линейно зависимы

Когда векторы столбцов коэффициентов  𝑎1,𝑎2...,𝑎𝑛  линейно зависимы, они образуют некоторое линейное подпространство размерности меньше, чем  𝑛 . И такая система совместна, только когда вектор  𝑏  принадлежит этому линейному подпространству. В этом случае система имеет бесконечное число решений. Если же вектор  𝑏  этому подпространству не принадлежит, система решений не имеет.

#### Для того что бы система уравнений была несовместна и не имела решений, вектор свободных членов должен принимать любое значение, за исключением равных векторам столбцов коэфициентов, тогда система будет иметь бесконечное колличество решений

проверим данное утверждение

подствим любой вектор свободных членов не равный векторам столбцов коэфициентов

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([2, 2, 3]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема несовместна'

подставим вектор равный одному из векторов столбцов коэфициентов

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 4, 7]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема имеет бесконечное количество решений'

### Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

будем подставлять свободные члены в матрицу, искать определители и находить x путем деления определителя исходной матрицы на матрицы со свободными членами

a)

In [16]:
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7]).reshape(-1, 1)

x1 = np.linalg.det(np.hstack((b, A[:,1].reshape(-1, 1)))) /  np.linalg.det(A)
x1


4.999999999999998

In [17]:
x2 = np.linalg.det(np.hstack((A[:,0].reshape(-1, 1), b))) /  np.linalg.det(A)
x2

1.9999999999999991

In [18]:
np.linalg.solve(A, b)

array([[5.],
       [2.]])

б)

In [19]:
A = np.array([[2, -1, 5], [1, 2, -3], [2, 4, 1]])
b = np.array([10, -2, 1]).reshape(-1, 1)

In [20]:
x_1 = np.linalg.det(np.hstack((b, A[:,1:]))) /  np.linalg.det(A)
x_1

2.6000000000000023

In [21]:
x_2 = np.linalg.det(np.hstack((A[:,:1], b, A[:,-1:]))) /  np.linalg.det(A)
x_2

-1.2285714285714293

In [22]:
x_3 = np.linalg.det(np.hstack((A[:,:2], b))) /  np.linalg.det(A)
x_3

0.7142857142857143

In [23]:
np.linalg.solve(A, b)

array([[ 2.6       ],
       [-1.22857143],
       [ 0.71428571]])

### Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а)

In [24]:
import pprint
import scipy
import scipy.linalg

A = scipy.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
P, L, U = scipy.linalg.lu(A)
print("A:")
pprint.pprint(A)

print("P (permutation):")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])
P (permutation):
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.8       , 1.        ]])
U:
array([[ 3.        , 26.        , 30.        ],
       [ 0.        , -8.33333333, -8.        ],
       [ 0.        ,  0.        ,  0.4       ]])


C:\Users\1\AppData\Local\Temp\ipykernel_5036\2016233810.py:5: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = scipy.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])


б)

In [25]:
B = scipy.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
P, L, U = scipy.linalg.lu(B)
print("B:")
pprint.pprint(B)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

B:
array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])
P:
array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])
L:
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.75      , -0.25      ,  1.        ,  0.        ],
       [ 0.25      ,  0.75      , -0.17073171,  1.        ]])
U:
array([[  4.        ,  22.        ,  53.        ,  33.        ],
       [  0.        ,  -6.        , -18.5       ,  -7.5       ],
       [  0.        ,   0.        , -15.375     ,  -8.625     ],
       [  0.        ,   0.        ,   0.        ,  -0.09756098]])


C:\Users\1\AppData\Local\Temp\ipykernel_5036\2255086693.py:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  B = scipy.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])


### Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [26]:
A = scipy.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
P, L, U = scipy.linalg.lu(A)
print("A:")
pprint.pprint(A)

print("P (permutation):")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 2,  1,  3],
       [11,  7,  5],
       [ 9,  8,  4]])
P (permutation):
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])
L:
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.81818182,  1.        ,  0.        ],
       [ 0.18181818, -0.12      ,  1.        ]])
U:
array([[11.        ,  7.        ,  5.        ],
       [ 0.        ,  2.27272727, -0.09090909],
       [ 0.        ,  0.        ,  2.08      ]])


C:\Users\1\AppData\Local\Temp\ipykernel_5036\482369979.py:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = scipy.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])


Ly=b

In [27]:
y1 = 1
y2 = -6 - 0.82
y3 = -5 -0.18 +0.12*y2
print(f'y1: {y1:.1f}, y2: {y2:.1f}, y3: {y3:.1f}')

y1: 1.0, y2: -6.8, y3: -6.0


Ux=y

In [28]:
x3 = y3/2.08
x2 = (y2 + 0.09 * x3)/ 2.27
x1 = (y1- 5*x3 - 7*x2)/11
print(f'x1: {x1:.1f}, x2: {x2:.1f}, x3: {x3:.1f}')

x1: 3.4, x2: -3.1, x3: -2.9
